exports.transactionsData = [
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 120,
    transactionDate: "05-01-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 75,
    transactionDate: "05-21-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 94,
    transactionDate: "05-21-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 10,
    transactionDate: "06-01-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 75,
    transactionDate: "06-21-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 200,
    transactionDate: "07-01-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 1,
    transactionDate: "07-04-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 80,
    transactionDate: "07-03-2022",
  },
  {
    customerId: 1,
    customerName: "ehtasham",
    transactionAmount: 224,
    transactionDate: "07-21-2022",
  },
  {
    customerId: 2,
    customerName: "Usman Faisal",
    transactionAmount: 125,
    transactionDate: "05-01-2022",
  },
  {
    customerId: 2,
    customerName: "Usman Faisal",
    transactionAmount: 75,
    transactionDate: "05-21-2022",
  },
  {
    customerId: 2,
    customerName: "Usman Faisal",
    transactionAmount: 10,
    transactionDate: "06-01-2022",
  },
  {
    customerId: 2,
    customerName: "Usman Faisal",
    transactionAmount: 75,
    transactionDate: "06-21-2022",
  },
  {
    customerId: 2,
    customerName: "Usman Faisal",
    transactionAmount: 200,
    transactionDate: "07-01-2022",
  },
  {
    customerId: 2,
    customerName: "Usman Faisal",
    transactionAmount: 224,
    transactionDate: "07-21-2022",
  },
  {
    customerId: 3,
    customerName: "Hamza",
    transactionAmount: 120,
    transactionDate: "06-21-2022",
  },
];
